[workspace]
resolver = "3"
members = [
    "sipc", "sipfmt",
]

[profile.release]
opt-level = "z"      # Can use "3" or "z" depending on goal (see below)
codegen-units = 1    # Better optimization, slower compile
lto = "fat"          # Link Time Optimization (full mode)
debug = false        # No debug symbols at all
strip = "symbols"    # Strip symbols for faster loading (requires Rust 1.71+)
overflow-checks = false
panic = "abort"      # No stack unwinding, smaller & faster
incremental = false  # Disable incremental builds

